# -*- coding: utf-8 -*-
"""HELLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLg1a8hq8PHq3guCPFvqE5ZPy03b4QFJ
"""

import streamlit as st

st.write ("hello world")

